//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ZephyrParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IZephyrParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ZephyrParserBaseListener : IZephyrParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ZephyrParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ZephyrParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementList([NotNull] ZephyrParser.StatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementList([NotNull] ZephyrParser.StatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ZephyrParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ZephyrParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecl([NotNull] ZephyrParser.DeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecl([NotNull] ZephyrParser.DeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.classBodyDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBodyDecl([NotNull] ZephyrParser.ClassBodyDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.classBodyDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBodyDecl([NotNull] ZephyrParser.ClassBodyDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.typedVarDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedVarDecl([NotNull] ZephyrParser.TypedVarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.typedVarDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedVarDecl([NotNull] ZephyrParser.TypedVarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDecl([NotNull] ZephyrParser.ClassDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDecl([NotNull] ZephyrParser.ClassDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] ZephyrParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] ZephyrParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.printStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintStmt([NotNull] ZephyrParser.PrintStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.printStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintStmt([NotNull] ZephyrParser.PrintStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] ZephyrParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] ZephyrParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.compound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound([NotNull] ZephyrParser.CompoundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.compound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound([NotNull] ZephyrParser.CompoundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] ZephyrParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] ZephyrParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] ZephyrParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] ZephyrParser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] ZephyrParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] ZephyrParser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDecl([NotNull] ZephyrParser.FuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDecl([NotNull] ZephyrParser.FuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.funcParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncParameters([NotNull] ZephyrParser.FuncParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.funcParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncParameters([NotNull] ZephyrParser.FuncParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.funcArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArguments([NotNull] ZephyrParser.FuncArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.funcArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArguments([NotNull] ZephyrParser.FuncArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] ZephyrParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] ZephyrParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.assignExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignExpr([NotNull] ZephyrParser.AssignExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.assignExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignExpr([NotNull] ZephyrParser.AssignExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.equality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality([NotNull] ZephyrParser.EqualityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.equality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality([NotNull] ZephyrParser.EqualityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] ZephyrParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] ZephyrParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] ZephyrParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] ZephyrParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] ZephyrParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] ZephyrParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ZephyrParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] ZephyrParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ZephyrParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] ZephyrParser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
